AWSTemplateFormatVersion: 2010-09-09
Description: 'auto scaling'
Resources:
  WebServerGroup:
    Type: 'AWS::AutoScaling::AutoScalingGroup'
    Properties:
      LaunchConfigurationName: !Ref LaunchConfig
      MinSize: '1'
      MaxSize: '3'
      AvailabilityZones:
        - us-east-2a
        - us-east-2b
        - us-east-2c
  LaunchConfig:
    Type: 'AWS::AutoScaling::LaunchConfiguration'
    Properties:
      KeyName: 'aws'
      ImageId: ami-063acf95dd32e67ea
      SecurityGroups:
        - !Ref InstanceSecurityGroup
      InstanceType: t2.micro
  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access and HTTP from the load balancer only
      VpcId: 'vpc-ef657487'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: '0.0.0.0/0'
